language: cpp

compiler:
  #- clang
  - gcc

before_install:
  # g++5
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq
  - sudo apt-get upgrade -y
  - sudo apt-get install -y libglew-dev libgl1-mesa-dev freeglut3-dev libjemalloc-dev
  - sudo apt-get install -y xorg-dev
  - sudo apt-get install -y cmake
  - sudo git clone https://github.com/glfw/glfw && mkdir build_glfw && cd build_glfw && cmake ../glfw && make -j4 && sudo make install
  - sudo git clone https://github.com/skaslev/gl3w && mkdir build_gl3w && cd build_gl3w && cmake ../gl3w && make && sudo make install
install:
  # g++5
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-5; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi

  # clang 3.8
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.8; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.8"; fi

script:
  - echo `$CXX --version`
  - make all
