[package]
name = "e2r"
version = "0.1.0"
authors = ["YL <yuan6liu@gmail.com>"]

[lib]
name = "e2rcore"
path = "core/core.rs"

# [[bin]]
# name = "e2r_core_bin"
# path = "core/src/driver.rs"

# [[bin]]
# name = "e2r_sandbox"
# path = "sandbox/src/sandbox0.rs"
